### ISSUE TITLE
unknown container name

### ISSUE THREAD

**Issue by bcarpio** [bwalex/fluent-plugin-docker-format#2]
I'm having an issue with td-agent and fluent-plugin-docker-format. 

td-agent: 2.1.4-0
fluent-plugin-docker-format: 0.2.3

The issue I am seeing is when I run a docker ps on a server running a container, clearly there is a name for the container. 

CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                                                                                                              NAMES
c36b69fd1481        itriage/bamboo:0.2.4   "/var/bamboo/bamboo    13 days ago         Up 51 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:9000->9000/tcp   bamboo

When I see the logs in ES I see this:

{"log":"2015/02/17 22:05:15.495912 [c36b69fd1481/yDNlspq6bt-000364] Started GET \"/\" from 10.40.70.96:48837\n","stream":"stderr","container_id":"c36b69fd1481e5a28e8b4ccbe34361e25d08f361562b0d28056505b9c166af64-json","container_name":"<unknown>","@timestamp":"2015-02-17T22:05:15+00:00"}

Any way to debug 'unknown' container ID?

Here is my td-agent.conf:

```
<source>
  type tail
  path /mnt/docker/containers/*/*-json.log
  pos_file /var/log/td-agent/fluentd-docker.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag docker.*
  format json
</source>

<match docker.mnt.docker.containers.*.*.log>
  type docker_format
  container_id ${tag_parts[5]}
  tag docker.all
</match>

<match docker.all>
  type elasticsearch
  logstash_format true
  flush_interval 10s # for testing
  hosts 10.10.10.10
</match>
```

**Comment by korya** [comment]
Modify  the `container_id` index in tag_parts from `5` to `4`.

```diff
 - container_id ${tag_parts[5]}
 + container_id ${tag_parts[4]}
```

**Comment by bcarpio** [comment]
Thanks a lot this fixed my issue.
